version: "3.7"
services:
  api:
    build: .
    container_name: fastapi_mock-api
    ports:
      - "${APP_PORT:-10000}:10000"
    volumes:
      - ".:/srv"
    networks:
      - internal
    hostname: api
networks:
  internal:
    external: false